<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu_left.phtml'); ?>
	    	<div id="contenu">
				<h1>Bienvenue sur Magic : The Awakening</h1>
				<p><strong>Magic: The Awakening</strong> est un jeu de r&ocirc;le en PHP, attention, bien que se déroulant dans l'univers de Magic: The Gathering, le système de jeu est très différent du célèbre jeu de cartes.<br />Dans le jeu, vous incarnez un aventurier parcourant les terres de Mercadia, vous pourrez affronter des monstres, ou découvrir des trésors insoupçonnés.<br /><br />
				Attention, pour l'instant, le bêta-test vient de commencer et de nombreuses fonctionnalités prévues ne sont pas implémentées.<br />Pour l'instant, le principal souci reste l'équilibrage afin d'offrir une expérience de jeu intéressante; n'hésitez pas à nous faire part de vos critiques ou conseils par mail (page contact) ou sur le forum.<br /><br />
				Merci de participer à la grande aventure de <strong>Magic: The Awakening</strong>, en vous souhaitant beaucoup de plaisir en parcourant notre jeu</p>
	    	</div>
			<br /><br />
<?php echo $this->render('footer.phtml'); ?>