<div id="menu_left">
	<div class="menu_left_content" id="menu_left_admin">
		<fieldset><legend>Administration</legend>
			<ul>
				<li><a href="<?php echo $this->baseUrl;?>/admin/utilisateur">G&eacute;rer Utilisateurs</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/admin/avatar">G&eacute;rer Avatars</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/admin/classe">G&eacute;rer Classes</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/admin/objet">G&eacute;rer Objets</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/admin/monstre">G&eacute;rer Monstres</a></li>
			</ul>
		</fieldset>
	</div>
</div>