<!--montagne-->
{
acc_marchand1:'<p>Hey! Appelez moi ma&icirc;tre!</p><br/><br/><input type="button" value="Acheter une comp&eacute;tence" onClick="getDonnees()"/><input type="button" value="Retour en ville" onClick="retour();"/>',
acc_marchand2:'<p style="margin-left:18px;margin-bottom:3px;">Que veux-tu apprendre jeune &eacute;l&egrave;ve!</p>',
acc_marchand3:'<p>La force des montagnes coule dans tes veines!</p>',
acc_marchand4:'<p>Les flammes du Dragon du fourneau te prot&grave;gent!</p><br/><input type="button" value="Retour en ville" onClick="retour();"/>',
}
