<!--Ile-->
{
acc_marchand1:'<p>Hum? Pla&icirc;t-il?</p><br/><br/><input type="button" value="Acheter une comp&eacute;tence" onClick="getDonnees()"/><input type="button" value="Retour en ville" onClick="retour();"/>',
acc_marchand2:'<p style="margin-left:18px;margin-bottom:3px;">Sauras-tu les utiliser ?</p>',
acc_marchand3:'<p>Un tourbillon prend place dans ton flux sanguin!</p>',
acc_marchand4:'<p>A une prochaine fois! Revenez quand vous voulez! Les eaux de Lorelia vous seront toujours cl&eacute;mentes...</p><br/><input type="button" value="Retour en ville" onClick="retour();"/>',
}

