<!--plaine-->
{
acc_marchand1:'<p>Bien le bonjour, &ecirc;tes vous prêt ?</p><br/><br/><input type="button" value="Acheter une comp&eacute;tence" onClick="getDonnees()"/><input type="button" value="Retour en ville" onClick="retour();"/>',
acc_marchand2:'<p style="margin-left:18px;margin-bottom:3px;">Laquelle de mes comp&eacute;tences vous plaira&icirc;t-il d\'avoir ?</p>',
acc_marchand3:'<p>Merci. Je sens votre force grandir!</p>',
acc_marchand4:'<p>Que la force des plaines de Goran soit avec vous! Aurevoir!</p><br/><input type="button" value="Retour en ville" onClick="retour();"/>',
}

