<!--forêt-->
{
acc_marchand1:'<p>Oui mon ma&icirc;tre ?</p><br/><br/><input type="button" value="Acheter une comp&eacute;tence" onClick="getDonnees()"/><input type="button" value="Retour en ville" onClick="retour();"/>',
acc_marchand2:'<p style="margin-left:18px;margin-bottom:3px;">Hoho, voici ce que mon &eacute;choppe vous offre.</p>',
acc_marchand3:'<p>Ooooh! Cette lumière en vous! L\'aventure ne fait que commencer!</p>',
acc_marchand4:'<p>Si vous &ecirc;tes perdu en for&ecirc;t les MAROS  vous indiqueront o&ugrave; se trouvent les portes de Ennadryl. Au revoir!</p><br/><input type="button" value="Retour en ville" onClick="retour();"/>',
}

