<!--marais-->
{
acc_marchand1:'<p>Si vous n\'&ecirc;tes pas ici pour tuer, partez ?!</p><br/><br/><input type="button" value="Acheter une comp&eacute;tence" onClick="getDonnees()"/><input type="button" value="Retour en ville" onClick="retour();"/>',
acc_marchand2:'<p style="margin-left:18px;margin-bottom:3px;">Vous osez!</p>',
acc_marchand3:'<p>Je sens le mal s\'emparer de vous!</p>',
acc_marchand4:'<p>Que cette nuit dans les marais de Sombre ne soit pas la dernière pour vous!</p><br/><input type="button" value="Retour en ville" onClick="retour();"/>',
}

